QxsqWebAdmin/Controllers/EditorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using QxsqBLL;
using QxsqWebAdmin.Models;
using QxsqDTO;

namespace QxsqWebAdmin.Controllers
{
    public class EditorController : BaseController
    {
      
        #region 网站管理员列表页
       
        public ActionResult EditorIndex(int? p)
        {


            string strwhere = "EditorId>0";
            string table = "QxsqEditor";

            Pager pager = new Pager();
            pager.PageSize = 2;
            pager.PageNo = p ?? 1;

            pager = EditorBll.GetEditorPager(pager, strwhere, table);
            ViewBag.PageNo = p ?? 1;
            ViewBag.PageCount = pager.PageCount;
            ViewBag.RecordCount = pager.Amount;


            return View(pager.Entity);
        }
        #endregion

        #region 网站管理员添加
        public ActionResult EditorAdd()
        {
            return View();

        }
        #endregion

        #region 网站管理员编辑
        public ActionResult EditorEdit(int EditorId)
        {
            string table="QxsqEditor";
            string strwhere="EditorId="+EditorId;
            EditorDto editorDto = EditorBll.GetOneEditorDto(table, strwhere);

            EditorEditViewModel model = new EditorEditViewModel();

            model.EditorUserName = editorDto.EditorUserName;
            model.EditorRealName = editorDto.EditorRealName;
            model.EditorId = editorDto.EditorId;
            

            return View(model);

        }

        #endregion

        #region 网站管理员新增动作
        [HttpPost]
        public ActionResult EditorInsert(EditorAddViewModel model)
        {
            EditorDto editorDto = new EditorDto();

            editorDto.EditorUserName = model.EditorUserName;
            editorDto.EditorRealName = model.EditorRealName;
            editorDto.EditorPassword = CommonTools.ToMd5(model.EditorPassword);
            editorDto.EditorRegTime = System.DateTime.Now;

            EditorBll.AddEditor(editorDto);

           return RedirectTo("/Editor/EditorIndex", "网站管理员添加成功了");
           //return RedirectToAction("EditorIndex");


        }
        #endregion

        #region 网站管理员更新动作
        [HttpPost]
        public ActionResult EditorUpdate(EditorEditViewModel model)
        {
            string table = "QxsqEditor";
            string strwhere = "EditorId=" + model.EditorId;
            EditorDto editorDto = EditorBll.GetOneEditorDto(table,strwhere);

            editorDto.EditorUserName = model.EditorUserName;
            editorDto.EditorRealName = model.EditorRealName;
            editorDto.EditorRegTime = System.DateTime.Now;

            EditorBll.UpdateEditorDto(editorDto);


            return RedirectToAction("EditorIndex");


        }

        #endregion

        #region 网站管理员删除动作
        public ActionResult EditorDelete(int EditorId)
        {
            string table = "QxsqEditor";
            string strwhere = "EditorId=" + EditorId;
            EditorBll.DeleteEditorDto(table, strwhere);

            return RedirectToAction("EditorIndex");

        }
        #endregion

    }
}

QxsqWebAdmin/Views/Editor/EditorAdd.cshtml
@model QxsqWebAdmin.Models.EditorAddViewModel
@{
    ViewBag.Title = "新增网站管理员";
}

<aside class="right-side">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">

        <!-- Small boxes (Stat box) -->
        <!-- /.row -->
        <!-- top row -->
        <div class="row">
            <div class="col-xs-12 connectedSortable">

            </div><!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">@ViewBag.Title</h3>
                    </div><!-- /.box-header -->
                    <!-- form start -->
                  @using (Html.BeginForm("EditorInsert", "Editor", FormMethod.Post))
    {     
                     
                       @Html.ValidationSummary(true)
                      <div class="box-body">
                            <div class="form-group">

                                @Html.LabelFor(model => model.EditorUserName)  @Html.ValidationMessageFor(model => model.EditorUserName)
                                @Html.TextBoxFor(model => model.EditorUserName, new { @class = "form-control" })
                              
                               
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.EditorRealName)  @Html.ValidationMessageFor(model => model.EditorRealName)
@Html.TextBoxFor(model => model.EditorRealName, new { @class = "form-control" })
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.EditorPassword)  @Html.ValidationMessageFor(model => model.EditorPassword)
@Html.PasswordFor(model => model.EditorPassword, new { @class = "form-control" })
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ConfirmPassword)  @Html.ValidationMessageFor(model => model.ConfirmPassword)
@Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                            </div>


                           


                           
                        </div><!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary btn-lg">保存</button>
                        </div>
                  }
                </div><!-- /.box -->



            </div><!--/.col (left) -->
            <!-- right column -->
            <!--/.col (right) -->
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</aside>

QxsqWebAdmin/Views/Editor/EditorEdit.cshtml
@model QxsqWebAdmin.Models.EditorEditViewModel
@{
    ViewBag.Title = "更新网站管理员信息";
}

<aside class="right-side">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">

        <!-- Small boxes (Stat box) -->
        <!-- /.row -->
        <!-- top row -->
        <div class="row">
            <div class="col-xs-12 connectedSortable">

            </div><!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">@ViewBag.Title</h3>
                    </div><!-- /.box-header -->
                    <!-- form start -->
                  @using (Html.BeginForm("EditorUpdate", "Editor", FormMethod.Post))
    {     
                      @Html.HiddenFor(model=>model.EditorId)
                     
                       @Html.ValidationSummary(true)
                      <div class="box-body">
                            <div class="form-group">

                                @Html.LabelFor(model => model.EditorUserName)  @Html.ValidationMessageFor(model => model.EditorUserName)
                                @Html.TextBoxFor(model => model.EditorUserName, new { @class = "form-control" })
                              
                               
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.EditorRealName)  @Html.ValidationMessageFor(model => model.EditorRealName)
@Html.TextBoxFor(model => model.EditorRealName, new { @class = "form-control" })
                            </div>

                           


                           


                           
                        </div><!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary btn-lg">保存</button>
                        </div>
                  }
                </div><!-- /.box -->



            </div><!--/.col (left) -->
            <!-- right column -->
            <!--/.col (right) -->
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</aside>

QxsqWebAdmin/Views/Editor/EditorIndex.cshtml
@{
    ViewBag.Title = "网站编辑设置";
}

<link href="/css/page.css" rel="stylesheet" type="text/css" />
<link href="/css/jquery-confirm.css" rel="stylesheet" type="text/css">

<aside class="right-side">
    <!-- Content Header (Page header) -->
    

    <!-- Main content -->
    <section class="content">

        <!-- Small boxes (Stat box) -->
        <!-- /.row -->
        <!-- top row -->
        <div class="row">
            <div class="col-xs-12 connectedSortable">

            </div><!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">网站管理员设置 <small>共 @ViewBag.RecordCount 条记录</small></h3>
                    
                        <div class="box-tools pull-right">
                          

                                <a href="@Url.Action("EditorAdd", "Editor")" class="btn btn-sm btn-primary" style="color:#ffffff"><i class="fa fa-plus"></i>  增加网站管理员</a>

                            
                        </div>
                    </div><!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">
   <table class="table table-hover">
                            <tr>
                                <th>序号</th>
                                <th>用户名</th>
                                <th>真实姓名</th>
                                <th>注册更新日期</th>
                                <th>操作</th>
                            </tr>

@foreach (var item in Model)
            {
                            <tr>
                                <td>@item.EditorId</td>
                                <td>@item.EditorUserName</td>
                                <td>@item.EditorRealName</td>
                                <td>@item.EditorRegTime</td>
                                <td>
                                    <a href="@Url.Action("EditorEdit", "Editor", new { EditorId = @item.EditorId })" class="btn btn-sm btn-success"><i class="fa fa fa-edit"></i>  编辑
                                    </a>  
                                    <button class="btn btn-sm btn-danger" onclick="DeleteEditor(@item.EditorId)"><i class="fa fa-trash-o"></i>  删除</button>
                                </td>
                            </tr>
}

                           
                        </table>
                    </div><!-- /.box-body -->
                    
                    <div class="box-footer clearfix">
                        <!-- Pagging -->
                        共 @ViewBag.RecordCount 条记录 <div class="SkyPager"></div>
                        <!-- EndPagging -->
                    </div>
                        
                    
                </div><!-- /.box -->
            </div>
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</aside>

    <!-- jQuery 2.0.2 -->

<script src="/js/jquery-confirm.js"></script>
<script src="/js/JSsite.js" type="text/javascript"></script>
<script src="/js/jquery.pager.js" type="text/javascript"></script>
@section JsBottom{

    <script type="text/javascript">

        var pageNo = @ViewBag.PageNo;
        var pageCount = @ViewBag.PageCount;
        var RecordCount=@ViewBag.RecordCount;

        $(function() {
           
            if (pageCount == 0) {
                 $(".SkyPager").hide();
                
            }
            $(".SkyPager").pager({ pagenumber: pageNo, pagecount: pageCount, buttonClickCallback: PageClick });
        });

        PageClick = function(no) {
            window.location = "?p=" + no;
        }



        

        function DeleteEditor(id){
            $.confirm({
                title: '确认删除!',
                content: '你确定要删除吗？!',
                confirmButton:'确定删除',
                cancelButton:'我后悔了',
                confirm: function(){
                    //alert('Confirmed!');
                    window.location = "/Editor/EditorDelete?EditorId="+id ;
                },
                cancel: function(){
                    
                }
            });
        
        }

    </script>



}