QxsqWebAdmin/Controllers/GuahaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using QxsqBLL;
using QxsqWebAdmin.Models;
using QxsqDTO;

namespace QxsqWebAdmin.Controllers
{
    public class GuahaoController : BaseController
    {
      

        #region 模块添加
        public ActionResult GuahaoAdd()
        {
            return View();

        }
        #endregion

        #region 模块新增动作
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult GuahaoInsert(GuahaoAddViewModel model)
        {
            GuahaoDto guahaoDto = new GuahaoDto();

            guahaoDto.GuahaoName = model.GuahaoName;
            guahaoDto.GuahaoTel = model.GuahaoTel;
            guahaoDto.GuahaoInfo = model.GuahaoInfo;
            guahaoDto.GuahaoDateTime = System.DateTime.Now;
            guahaoDto.GuahaoTime = model.GuahaoTime;
            guahaoDto.GuahaoStatus = model.GuahaoStatus;
            guahaoDto.GuahaoDoctor = model.GuahaoDoctor;
            guahaoDto.GuahaoGroup = model.GuahaoGroup;


            GuahaoBll.AddGuahao(guahaoDto);


            return RedirectToAction("GuahaoIndex");


        }
        #endregion

        #region 模块列表页

        public ActionResult GuahaoIndex(int? p,int? status)
        {
            int GuahaoStatus = status ?? 0;
            string strwhere = "";

            if (GuahaoStatus == 0)
            {
                strwhere = "GuahaoId>0";
            }
            else
            {
                strwhere = "GuahaoId>0 and GuahaoStatus=" + GuahaoStatus;
            }

           

            string table = "QxsqGuahao";

            Pager pager = new Pager();
            pager.PageSize = 20;
            pager.PageNo = p ?? 1;

            pager = GuahaoBll.GetGuahaoPager(pager, strwhere, table);
            ViewBag.PageNo = p ?? 1;
            ViewBag.PageCount = pager.PageCount;
            ViewBag.RecordCount = pager.Amount;


            return View(pager.Entity);
        }
        #endregion

        #region 模块删除动作
        public ActionResult GuahaoDelete(int GuahaoId)
        {
            string table = "QxsqGuahao";
            string strwhere = "GuahaoId=" + GuahaoId;
            GuahaoBll.DeleteGuahaoDto(table, strwhere);

            return RedirectToAction("GuahaoIndex");

        }
        #endregion

        #region 模块编辑
        public ActionResult GuahaoEdit(int GuahaoId)
        {
            string table = "QxsqGuahao";
            string strwhere = "GuahaoId=" + GuahaoId;
            GuahaoDto guahaoDto = GuahaoBll.GetOneGuahaoDto(table, strwhere);

            GuahaoEditViewModel model = new GuahaoEditViewModel();

            model.GuahaoName = guahaoDto.GuahaoName;
            model.GuahaoTel = guahaoDto.GuahaoTel;
            model.GuahaoInfo = guahaoDto.GuahaoInfo;
            model.GuahaoDateTime = System.DateTime.Now;
            model.GuahaoTime = System.DateTime.Now;
            model.GuahaoStatus = guahaoDto.GuahaoStatus;
            model.GuahaoDoctor = guahaoDto.GuahaoDoctor;
            model.GuahaoGroup = guahaoDto.GuahaoGroup;
            model.GuahaoId = guahaoDto.GuahaoId;



            return View(model);

        }

        #endregion

        #region 模块更新动作
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult GuahaoUpdate(GuahaoEditViewModel model)
        {
            string table = "QxsqGuahao";
            string strwhere = "GuahaoId=" + model.GuahaoId;
            GuahaoDto guahaoDto = GuahaoBll.GetOneGuahaoDto(table, strwhere);

            guahaoDto.GuahaoName = model.GuahaoName;
            guahaoDto.GuahaoTel = model.GuahaoTel;
            guahaoDto.GuahaoInfo = model.GuahaoInfo;
            guahaoDto.GuahaoDateTime = System.DateTime.Now;
            guahaoDto.GuahaoTime = System.DateTime.Now;
            guahaoDto.GuahaoStatus = model.GuahaoStatus;
            guahaoDto.GuahaoDoctor = model.GuahaoDoctor;
            guahaoDto.GuahaoGroup = model.GuahaoGroup;

            GuahaoBll.UpdateGuahaoDto(guahaoDto);


            return RedirectToAction("GuahaoIndex");


        }

        #endregion
    }
}

QxsqWebAdmin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using QxsqBLL;
using QxsqWebAdmin.Models;
using QxsqDTO;

namespace QxsqWebAdmin.Controllers
{
    public class UserController : BaseController
    {
      
        #region 客户列表页
       
        public ActionResult UserIndex(int? p)
        {


            string strwhere = "UserId>0";
            string table = "JkptUser";

            Pager pager = new Pager();
            pager.PageSize = 20;
            pager.PageNo = p ?? 1;

            pager = UserBll.GetUserPager(pager, strwhere, table);
            ViewBag.PageNo = p ?? 1;
            ViewBag.PageCount = pager.PageCount;
            ViewBag.RecordCount = pager.Amount;


            return View(pager.Entity);
        }
        #endregion

        #region 客户添加
        public ActionResult UserAdd()
        {
            ViewData["UserSexList"] = UserCommonBll.GetUserInfoForSelect("UserSex");
            ViewData["UserHujiList"] = UserCommonBll.GetUserInfoForSelect("UserHuji");
            ViewData["UserMinzuList"] = UserCommonBll.GetUserInfoForSelect("UserMinzu");
            ViewData["UserZhiyeList"] = UserCommonBll.GetUserInfoForSelect("UserZhiye");
            ViewData["UserHunyinList"] = UserCommonBll.GetUserInfoForSelect("UserHunyin");
            ViewData["UserWenhuaList"] = UserCommonBll.GetUserInfoForSelect("UserWenhua");
            return View();

        }
        #endregion

        #region 客户编辑
        public ActionResult UserEdit(int UserId)
        {
            string table = "JkptUser";
            string strwhere="UserId="+UserId;
            UserDto userDto = UserBll.GetOneUserDto(table, strwhere);

            UserEditViewModel model = new UserEditViewModel();

            model.UserId = userDto.UserId;
            model.UserPassword = userDto.UserPassword;
            model.UserName = userDto.UserName;
            model.UserSex = userDto.UserSex;
            model.UserBirthday = userDto.UserBirthday;
            model.UserNumber = userDto.UserNumber;
            model.UserTel = userDto.UserTel;
            model.UserFirstPerson = userDto.UserFirstPerson;
            model.UserFirstPersonTel = userDto.UserFirstPersonTel;
            model.UserJiedaoName = userDto.UserJiedaoName;
            model.UserJuweihuiName = userDto.UserJuweihuiName;
            model.UserHuji = userDto.UserHuji;
            model.UserMinzu = userDto.UserMinzu;
            model.UserWenhua = userDto.UserWenhua;
            model.UserZhiye = userDto.UserZhiye;
            model.UserHunyin = userDto.UserHunyin;
            model.UserDoctor = userDto.UserDoctor;
            model.UserGroup = userDto.UserGroup;
            model.UserClass = userDto.UserClass;
            model.UserNowAddress = userDto.UserNowAddress;
            model.UserOldAddress = userDto.UserOldAddress;
            model.UserJobGroup = userDto.UserJobGroup;
            model.UserDiy1 = userDto.UserDiy1;
            model.UserDiy2 = userDto.UserDiy2;
            model.UserDiy3 = userDto.UserDiy3;
            model.UserDiy4 = userDto.UserDiy4;
            model.UserDiy5 = userDto.UserDiy5;
            model.UserDiy6 = userDto.UserDiy6;
            model.UserBeizhu = userDto.UserBeizhu;

            return View(model);

        }

        #endregion

        #region 客户新增动作
        [HttpPost]
        public ActionResult UserInsert(UserAddViewModel model)
        {
            UserDto userDto = new UserDto();

            userDto.UserPassword = model.UserPassword;
            userDto.UserName = model.UserName;
            userDto.UserSex = model.UserSex;
            userDto.UserBirthday = model.UserBirthday;
            userDto.UserNumber = model.UserNumber;
            userDto.UserTel = model.UserTel;
            userDto.UserFirstPerson = model.UserFirstPerson;
            userDto.UserFirstPersonTel = model.UserFirstPersonTel;
            userDto.UserJiedaoName = model.UserJiedaoName;
            userDto.UserJuweihuiName = model.UserJuweihuiName;
            userDto.UserHuji = model.UserHuji;
            userDto.UserMinzu = model.UserMinzu;
            userDto.UserWenhua = model.UserWenhua;
            userDto.UserZhiye = model.UserZhiye;
            userDto.UserHunyin = model.UserHunyin;
            userDto.UserDoctor = model.UserDoctor;
            userDto.UserGroup = model.UserGroup;
            userDto.UserClass = model.UserClass;
            userDto.UserNowAddress = model.UserNowAddress;
            userDto.UserOldAddress = model.UserOldAddress;
            userDto.UserJobGroup = model.UserJobGroup;
            userDto.UserDiy1 = model.UserDiy1;
            userDto.UserDiy2 = model.UserDiy2;
            userDto.UserDiy3 = model.UserDiy3;
            userDto.UserDiy4 = model.UserDiy4;
            userDto.UserDiy5 = model.UserDiy5;
            userDto.UserDiy6 = model.UserDiy6;
            userDto.UserBeizhu = model.UserBeizhu;

            UserBll.AddUser(userDto);

           return RedirectTo("/User/UserIndex", "客户添加成功了");
           //return RedirectToAction("UserIndex");


        }
        #endregion

        #region 客户更新动作
        [HttpPost]
        public ActionResult UserUpdate(UserEditViewModel model)
        {
            string table = "JkptUser";
            string strwhere = "UserId=" + model.UserId;
            UserDto userDto = UserBll.GetOneUserDto(table,strwhere);
            userDto.UserPassword = model.UserPassword;
            userDto.UserName = model.UserName;
            userDto.UserSex = model.UserSex;
            userDto.UserBirthday = model.UserBirthday;
            userDto.UserNumber = model.UserNumber;
            userDto.UserTel = model.UserTel;
            userDto.UserFirstPerson = model.UserFirstPerson;
            userDto.UserFirstPersonTel = model.UserFirstPersonTel;
            userDto.UserJiedaoName = model.UserJiedaoName;
            userDto.UserJuweihuiName = model.UserJuweihuiName;
            userDto.UserHuji = model.UserHuji;
            userDto.UserMinzu = model.UserMinzu;
            userDto.UserWenhua = model.UserWenhua;
            userDto.UserZhiye = model.UserZhiye;
            userDto.UserHunyin = model.UserHunyin;
            userDto.UserDoctor = model.UserDoctor;
            userDto.UserGroup = model.UserGroup;
            userDto.UserClass = model.UserClass;
            userDto.UserNowAddress = model.UserNowAddress;
            userDto.UserOldAddress = model.UserOldAddress;
            userDto.UserJobGroup = model.UserJobGroup;
            userDto.UserDiy1 = model.UserDiy1;
            userDto.UserDiy2 = model.UserDiy2;
            userDto.UserDiy3 = model.UserDiy3;
            userDto.UserDiy4 = model.UserDiy4;
            userDto.UserDiy5 = model.UserDiy5;
            userDto.UserDiy6 = model.UserDiy6;
            userDto.UserBeizhu = model.UserBeizhu;



            UserBll.UpdateUserDto(userDto);


            return RedirectToAction("UserIndex");


        }

        #endregion

        #region 客户删除动作
        public ActionResult UserDelete(int UserId)
        {
            string table = "JkptUser";
            string strwhere = "UserId=" + UserId;
            UserBll.DeleteUserDto(table, strwhere);

            return RedirectToAction("UserIndex");

        }
        #endregion

    }
}

QxsqWebAdmin/Views/User/UserAdd.cshtml
@model QxsqWebAdmin.Models.UserAddViewModel
@{
    ViewBag.Title = "个人基本信息录入";
}

<aside class="right-side">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">

        <!-- Small boxes (Stat box) -->
        <!-- /.row -->
        <!-- top row -->
        <div class="row">
            <div class="col-xs-12 connectedSortable">

            </div><!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title txt-center">@ViewBag.Title</h3>
                    </div><!-- /.box-header -->
                    <!-- form start -->
                  @using (Html.BeginForm("UserInsert", "User", FormMethod.Post, new { @class="form-inline"}))
                  {     
                     
                       @Html.ValidationSummary(true)

    <div class="box-body">
        @Html.HiddenFor(model => model.UserDoctor, new { value = "1" })
        @Html.HiddenFor(model => model.UserGroup, new { @value = "1" })

            <div class="col-xs-3">
                <div class="input-group">
                    <span class="input-group-addon">@Html.LabelFor(model => model.UserName) </span>
                    @Html.TextBoxFor(model => model.UserName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserName)
                </div>
            </div>

        <div class="col-xs-3">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserSex) </span>
                @Html.DropDownListFor(model => model.UserSex, ViewData["UserSexList"] as IEnumerable<SelectListItem>, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserSex)
            </div>
        </div>

        <div class="col-xs-3">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserHuji) </span>
                @Html.DropDownListFor(model => model.UserHuji, ViewData["UserHujiList"] as IEnumerable<SelectListItem>, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserHuji)
            </div>
        </div>
        <div class="col-xs-3">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserMinzu) </span>
                @Html.DropDownListFor(model => model.UserMinzu, ViewData["UserMinzuList"] as IEnumerable<SelectListItem>, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserMinzu)
            </div>
        </div>
            

       

        
        <br /><br /><br />

        <div class="col-xs-3">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserHunyin) </span>
                @Html.DropDownListFor(model => model.UserHunyin, ViewData["UserHunyinList"] as IEnumerable<SelectListItem>, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserHunyin)
            </div>
        </div>


        <div class="col-xs-3">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserWenhua) </span>
                @Html.DropDownListFor(model => model.UserWenhua, ViewData["UserWenhuaList"] as IEnumerable<SelectListItem>, new { @class = "form-control" })
   @Html.ValidationMessageFor(model => model.UserWenhua)
            </div>
        </div>
        <div class="col-xs-6">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserBirthday) </span>
                @Html.TextBoxFor(model => model.UserBirthday, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserBirthday)
            </div>
        </div>

        <br /><br /><br />
        <div class="col-xs-6">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserZhiye) </span>
                @Html.DropDownListFor(model => model.UserZhiye, ViewData["UserZhiyeList"] as IEnumerable<SelectListItem>, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserZhiye)
            </div>
        </div>


        <div class="col-xs-6">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserJobGroup) </span>
                @Html.TextBoxFor(model => model.UserJobGroup, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserJobGroup)
            </div>
        </div>
        <br /><br /><br />
        <div class="col-xs-6">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserNumber) </span>
                @Html.TextBoxFor(model => model.UserNumber, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserNumber)
            </div>
        </div>


        <div class="col-xs-6">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserTel) </span>
                @Html.TextBoxFor(model => model.UserTel, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserTel)
            </div>
        </div>


        <br /><br /><br />

        <div class="col-xs-6">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserFirstPerson) </span>
                @Html.TextBoxFor(model => model.UserFirstPerson, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserFirstPerson)
            </div>
        </div>


        <div class="col-xs-6">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserFirstPersonTel) </span>
                @Html.TextBoxFor(model => model.UserFirstPersonTel, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserFirstPersonTel)
            </div>
        </div>

        <br /><br /><br />

        <div class="col-xs-6">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserNowAddress) </span>
                @Html.TextBoxFor(model => model.UserNowAddress, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserNowAddress)
            </div>
        </div>


        <div class="col-xs-6">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserOldAddress) </span>
                @Html.TextBoxFor(model => model.UserOldAddress, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserOldAddress)
            </div>
        </div>
        <br /><br /><br />

        <div class="col-xs-6">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserJiedaoName) </span>
                @Html.TextBoxFor(model => model.UserJiedaoName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserJiedaoName)
            </div>
        </div>


        <div class="col-xs-6">
            <div class="input-group">
                <span class="input-group-addon">@Html.LabelFor(model => model.UserJuweihuiName) </span>
                @Html.TextBoxFor(model => model.UserJuweihuiName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserJuweihuiName)
            </div>
        </div>
        <br /><br /><br />
          
        
                          </div><!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">立刻保存</button>
                        </div>
                  }
                </div><!-- /.box -->



            </div><!--/.col (left) -->
            <!-- right column -->
            <!--/.col (right) -->
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</aside>

QxsqWebAdmin/Views/User/UserEdit.cshtml
@model QxsqWebAdmin.Models.GuahaoEditViewModel
@{
    ViewBag.Title = "挂号编辑";
}

<link href="/umeditor/themes/default/css/umeditor.css" type="text/css" rel="stylesheet">

<script type="text/javascript" charset="utf-8" src="/umeditor/umeditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="/umeditor/umeditor.min.js"></script>
<script type="text/javascript" src="/umeditor/lang/zh-cn/zh-cn.js"></script>

<aside class="right-side">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">

        <!-- Small boxes (Stat box) -->
        <!-- /.row -->
        <!-- top row -->
        <div class="row">
            <div class="col-xs-12 connectedSortable">

            </div><!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">@ViewBag.Title</h3>
                    </div><!-- /.box-header -->
                    <!-- form start -->
                  @using (Html.BeginForm("GuahaoUpdate", "Guahao", FormMethod.Post))
    {     
                      @Html.HiddenFor(model=>model.GuahaoId)
                       @Html.ValidationSummary(true)
                      <div class="box-body">
                            <div class="form-group">

                                @Html.LabelFor(model => model.GuahaoName)  @Html.ValidationMessageFor(model => model.GuahaoName)
                                @Html.TextBoxFor(model => model.GuahaoName, new { @class = "form-control" })
                              
                               
                            </div>
                          <div class="form-group">

                              @Html.LabelFor(model => model.GuahaoTime)  @Html.ValidationMessageFor(model => model.GuahaoTime)
                              @Html.EditorFor(model => model.GuahaoTime, new { @class = "form-control" })


                          </div>
                          <div class="form-group">

                              @Html.LabelFor(model => model.GuahaoTel)  @Html.ValidationMessageFor(model => model.GuahaoTel)
                              @Html.EditorFor(model => model.GuahaoTel, new { @class = "form-control" })


                          </div>


                          <div class="form-group">

                              @Html.LabelFor(model => model.GuahaoInfo)  @Html.ValidationMessageFor(model => model.GuahaoInfo)
                              @Html.TextAreaFor(model => model.GuahaoInfo, new { @class = "form-control" })


                          </div>

                           
                         
                   
                       
                           
                        

                           
                        </div><!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">立刻保存</button>
                        </div>
                  }
                </div><!-- /.box -->



            </div><!--/.col (left) -->
            <!-- right column -->
            <!--/.col (right) -->
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</aside>

<script src="/js/ajaxfileupload.js"></script>

<script type="text/javascript">
    //实例化编辑器
    var um = UM.getEditor('myEditor');

    
</script>

QxsqWebAdmin/Views/User/UserIndex.cshtml
@{
    ViewBag.Title = "客户列表";
}

<link href="/css/page.css" rel="stylesheet" type="text/css" />
<link href="/css/jquery-confirm.css" rel="stylesheet" type="text/css">

<aside class="right-side">
    <!-- Content Header (Page header) -->
    

    <!-- Main content -->
    <section class="content">
   
        <!-- Small boxes (Stat box) -->
        <!-- /.row -->
        <!-- top row -->
        <div class="row">
            <div class="col-xs-12 connectedSortable">

            </div><!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">@ViewBag.Title <small>共 @ViewBag.RecordCount 条记录</small></h3>
                    
                        <div class="box-tools pull-right">


                            <a href="@Url.Action("UserAdd", "User")" class="btn btn-sm btn-primary" style="color:#ffffff"><i class="fa fa-plus"></i> 新增客户</a>


                        </div>
                       
                    </div><!-- /.box-header -->
                   
                    <h4>
                        状态类型：
                      
                        <a href="/Guahao/GuahaoIndex?status=0" class="btn btn-sm btn-primary">全部</a>
                        <a href="/Guahao/GuahaoIndex?status=1" class="btn btn-sm btn-warning">孕妇</a>
                        <a href="/Guahao/GuahaoIndex?status=2" class="btn btn-sm btn-info">儿童</a>
                        <a href="/Guahao/GuahaoIndex?status=3" class="btn btn-sm btn-danger">高血压</a>
                        <a href="/Guahao/GuahaoIndex?status=3" class="btn btn-sm btn-danger">糖尿病</a>
                    </h4> <div class="box-body table-responsive no-padding">
   <table class="table table-hover">
                            <tr>
                                <th>序号</th>
                                <th>患者姓名</th>   
                                <th>患者手机</th>                             
                                <th>患者性别</th>
                                <th>操作</th>
                            </tr>

@foreach (var item in Model)
            {
                            <tr>
                                <td>@item.UserId</td>
                                <td>@item.UserName</td>
                                <td>@item.UserTel</td>
                           
                                <td>@item.UserSex </td>
                                <td>编辑，删除</td>
                              
                            </tr>
}

                           
                        </table>
                    </div><!-- /.box-body -->
                    
                    <div class="box-footer clearfix">
                        <!-- Pagging -->
                        共 @ViewBag.RecordCount 条记录 <div class="SkyPager"></div>
                        <!-- EndPagging -->
                    </div>
                        
                    
                </div><!-- /.box -->
            </div>
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</aside>

    <!-- jQuery 2.0.2 -->

<script src="/js/jquery-confirm.js"></script>
<script src="/js/JSsite.js" type="text/javascript"></script>
<script src="/js/jquery.pager.js" type="text/javascript"></script>
@section JsBottom{

    <script type="text/javascript">

        var pageNo = @ViewBag.PageNo;
        var pageCount = @ViewBag.PageCount;
        var RecordCount=@ViewBag.RecordCount;

        $(function() {
           
            if (pageCount == 0) {
                 $(".SkyPager").hide();
                
            }
            $(".SkyPager").pager({ pagenumber: pageNo, pagecount: pageCount, buttonClickCallback: PageClick });
        });

        PageClick = function(no) {
            window.location = "?p=" + no;
        }


        function GuahaoPay(guahaoId,value) {
            var table="QxsqGuahao";
            var strwhere="GuahaoId="+guahaoId;
            var columnname="GuahaoStatus";
            var columnvalue=value;
            var url = '@Url.Action("SetModelByAjax", "Guahao")?table='+table+'&strwhere='+strwhere+'&columnname='+columnname+"&columnvalue="+columnvalue;
            
            
            $.getJSON(url, function(data) {

                window.location.reload();
            });
        
        }
        function DeleteGuahao(id){
            $.confirm({
                title: '确认删除!',
                content: '你确定要删除吗？!',
                confirmButton:'确定删除',
                cancelButton:'我后悔了',
                confirm: function(){
                    //alert('Confirmed!');
                    window.location = "/Guahao/GuahaoDelete?GuahaoId="+id ;
                },
                cancel: function(){
                    
                }
            });
        
        }

    </script>



}