QxsqWebAdmin/Controllers/ArticleClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using QxsqBLL;
using QxsqWebAdmin.Models;
using QxsqDTO;

namespace QxsqWebAdmin.Controllers
{
    public class ArticleClassController : BaseController
    {
      
        #region 文章类别列表页
       
        public ActionResult ArticleClassIndex(int? p)
        {


            string strwhere = "ArticleClassId>0";
            string table = "QxsqArticleClass";

            Pager pager = new Pager();
            pager.PageSize = 2;
            pager.PageNo = p ?? 1;

            pager = ArticleClassBll.GetArticleClassPager(pager, strwhere, table);
            ViewBag.PageNo = p ?? 1;
            ViewBag.PageCount = pager.PageCount;
            ViewBag.RecordCount = pager.Amount;


            return View(pager.Entity);
        }
        #endregion

        #region 文章类别添加
        public ActionResult ArticleClassAdd()
        {
            return View();

        }
        #endregion

        #region 文章类别编辑
        public ActionResult ArticleClassEdit(int ArticleClassId)
        {
            string table="QxsqArticleClass";
            string strwhere="ArticleClassId="+ArticleClassId;
            ArticleClassDto editorDto = ArticleClassBll.GetOneArticleClassDto(table, strwhere);

            ArticleClassEditViewModel model = new ArticleClassEditViewModel();

            model.ArticleClassName = editorDto.ArticleClassName;
            model.ArticleClassId = editorDto.ArticleClassId;
            

            return View(model);

        }

        #endregion

        #region 文章类别新增动作
        [HttpPost]
        public ActionResult ArticleClassInsert(ArticleClassAddViewModel model)
        {
            ArticleClassDto editorDto = new ArticleClassDto();

            editorDto.ArticleClassName = model.ArticleClassName;
           

            ArticleClassBll.AddArticleClass(editorDto);

            return RedirectTo("/ArticleClass/ArticleClassIndex", "文章类别添加成功了");
           // return RedirectToAction("ArticleClassIndex");


        }
        #endregion

        #region 文章类别更新动作
        [HttpPost]
        public ActionResult ArticleClassUpdate(ArticleClassEditViewModel model)
        {
            string table = "QxsqArticleClass";
            string strwhere = "ArticleClassId=" + model.ArticleClassId;
            ArticleClassDto editorDto = ArticleClassBll.GetOneArticleClassDto(table,strwhere);

            editorDto.ArticleClassName = model.ArticleClassName;


            ArticleClassBll.UpdateArticleClassDto(editorDto);


            return RedirectToAction("ArticleClassIndex");


        }

        #endregion

        #region 文章类别删除动作
        public ActionResult ArticleClassDelete(int ArticleClassId)
        {
            string table = "QxsqArticleClass";
            string strwhere = "ArticleClassId=" + ArticleClassId;
            ArticleClassBll.DeleteArticleClassDto(table, strwhere);

            return RedirectToAction("ArticleClassIndex");

        }
        #endregion

    }
}

QxsqWebAdmin/Views/ArticleClass/ArticleClassAdd.cshtml
@model QxsqWebAdmin.Models.ArticleClassAddViewModel
@{
    ViewBag.Title = "新增新闻类别设置";
}

<aside class="right-side">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">

        <!-- Small boxes (Stat box) -->
        <!-- /.row -->
        <!-- top row -->
        <div class="row">
            <div class="col-xs-12 connectedSortable">

            </div><!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">@ViewBag.Title</h3>
                    </div><!-- /.box-header -->
                    <!-- form start -->
                  @using (Html.BeginForm("ArticleClassInsert", "ArticleClass", FormMethod.Post))
    {     
                     
                       @Html.ValidationSummary(true)
                      <div class="box-body">
                            <div class="form-group">

                                @Html.LabelFor(model => model.ArticleClassName)  @Html.ValidationMessageFor(model => model.ArticleClassName)
                                @Html.TextBoxFor(model => model.ArticleClassName, new { @class = "form-control" })
                              
                               
                            </div>

                           
                           
                        </div><!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">立刻保存</button>
                        </div>
                  }
                </div><!-- /.box -->



            </div><!--/.col (left) -->
            <!-- right column -->
            <!--/.col (right) -->
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</aside>

QxsqWebAdmin/Views/ArticleClass/ArticleClassEdit.cshtml
@model QxsqWebAdmin.Models.ArticleClassEditViewModel
@{
    ViewBag.Title = "新闻类别设置编辑";
}

<aside class="right-side">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">

        <!-- Small boxes (Stat box) -->
        <!-- /.row -->
        <!-- top row -->
        <div class="row">
            <div class="col-xs-12 connectedSortable">

            </div><!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">@ViewBag.Title</h3>
                    </div><!-- /.box-header -->
                    <!-- form start -->
                  @using (Html.BeginForm("ArticleClassUpdate", "ArticleClass", FormMethod.Post))
    {     
                      @Html.HiddenFor(model=>model.ArticleClassId)
                     
                       @Html.ValidationSummary(true)
                      <div class="box-body">
                            <div class="form-group">

                                @Html.LabelFor(model => model.ArticleClassName)  @Html.ValidationMessageFor(model => model.ArticleClassName)
                                @Html.TextBoxFor(model => model.ArticleClassName, new { @class = "form-control" })
                              
                               
                            </div>
                       
                        </div><!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary btn-lg">保存</button>
                        </div>
                  }
                </div><!-- /.box -->



            </div><!--/.col (left) -->
            <!-- right column -->
            <!--/.col (right) -->
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</aside>

QxsqWebAdmin/Views/ArticleClass/ArticleClassIndex.cshtml
@{
    ViewBag.Title = "新闻类别设置";
}

<link href="/css/page.css" rel="stylesheet" type="text/css" />
<link href="/css/jquery-confirm.css" rel="stylesheet" type="text/css">

<aside class="right-side">
    <!-- Content Header (Page header) -->
    

    <!-- Main content -->
    <section class="content">

        <!-- Small boxes (Stat box) -->
        <!-- /.row -->
        <!-- top row -->
        <div class="row">
            <div class="col-xs-12 connectedSortable">

            </div><!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">@ViewBag.Title <small>共 @ViewBag.RecordCount 条记录</small></h3>
                    
                        <div class="box-tools pull-right">
                          

                                <a href="@Url.Action("ArticleClassAdd", "ArticleClass")" class="btn btn-sm btn-primary" style="color:#ffffff"><i class="fa fa-plus"></i>  增加新闻类别</a>

                            
                        </div>
                    </div><!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">
   <table class="table table-hover">
                            <tr>
                                <th>序号</th>
                                <th>新闻类别</th>

                                <th>操作</th>
                            </tr>

@foreach (var item in Model)
            {
                            <tr>
                                <td>@item.ArticleClassId</td>
                                <td>@item.ArticleClassName</td>

                                <td>
                                    <a href="@Url.Action("ArticleClassEdit", "ArticleClass", new { ArticleClassId = @item.ArticleClassId })"  class="btn btn-sm btn-success"><i class="fa fa fa-edit"></i>  编辑
                                    </a>  
                                    <button class="btn btn-sm btn-danger" onclick="DeleteArticleClass(@item.ArticleClassId)"><i class="fa fa-trash-o"></i>  删除</button>
                                </td>
                            </tr>
}

                           
                        </table>
                    </div><!-- /.box-body -->
                    
                    <div class="box-footer clearfix">
                        <!-- Pagging -->
                        共 @ViewBag.RecordCount 条记录 <div class="SkyPager"></div>
                        <!-- EndPagging -->
                    </div>
                        
                    
                </div><!-- /.box -->
            </div>
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</aside>

    <!-- jQuery 2.0.2 -->

<script src="/js/jquery-confirm.js"></script>
<script src="/js/JSsite.js" type="text/javascript"></script>
<script src="/js/jquery.pager.js" type="text/javascript"></script>
@section JsBottom{

    <script type="text/javascript">

        var pageNo = @ViewBag.PageNo;
        var pageCount = @ViewBag.PageCount;
        var RecordCount=@ViewBag.RecordCount;

        $(function() {
           
            if (pageCount == 0) {
                 $(".SkyPager").hide();
                
            }
            $(".SkyPager").pager({ pagenumber: pageNo, pagecount: pageCount, buttonClickCallback: PageClick });
        });

        PageClick = function(no) {
            window.location = "?p=" + no;
        }



        

        function DeleteArticleClass(id){
            $.confirm({
                title: '确认删除!',
                content: '你确定要删除吗？!',
                confirmButton:'确定删除',
                cancelButton:'我后悔了',
                confirm: function(){
                    //alert('Confirmed!');
                    window.location = "/ArticleClass/ArticleClassDelete?ArticleClassId="+id ;
                },
                cancel: function(){
                    
                }
            });
        
        }

    </script>



}